# Amira
# Generated by Amira 6.3.0
proc dataBox {inputBrain stdBrain doc} {
set box1 [$inputBrain getBoundingBox]; set box2 [$inputBrain getBoundingBox]; set box3 [$stdBrain getBoundingBox];
set outfile [open $doc w]
puts $outfile "$box1\n$box2\n$box3"
close $outfile
}

proc niiGeneration {saveDir inputBrain standardBrain doc t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15} {
set hideNewModules 0
[ load $inputBrain ] setLabel Input; Input fire; 
[ load $standardBrain ] setLabel Std; Std fire;
dataBox Input Std $doc

## do local registration
Input setTransform $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 $t9 $t10 $t11 $t12 $t13 $t14 $t15


## use input as refernece and applyTransform
remove applyTransform
create HxApplyTransform "applyTransform"
"applyTransform" data connect Input
"applyTransform"  reference connect Std
"applyTransform" fire
"applyTransform" interpolation setIndex 0 1
"applyTransform" mode setValue 0
"applyTransform" preserve setValue 0
"applyTransform" paddingValue setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"applyTransform" paddingValue setValue 0 0
#"applyTransform" applyTransformToResult 0
[ {applyTransform} action hit ; {applyTransform} fire ; {applyTransform} getResult ] setLabel {InputTransform}



# save transform and crop brain
set saveFile "$saveDir/[file rootname [file tail [Input parameters Filename getValue]]]_affine.nii"
InputTransform parameters setValue Filename $saveFile
InputTransform parameters setValue SaveInfo "Nifti"
InputTransform save
#InpuTransform exportData Nifti $saveFile


set saveFile "$saveDir/[file rootname [file tail [Input parameters Filename getValue]]]_affine_std.nii"
Std parameters setValue Filename $saveFile
Std parameters setValue SaveInfo "Nifti"
Std save
#Std exportData Nifti $saveFile


#set doc "$saveDir/[file rootname [file tail [Input parameters Filename getValue]]]_affine.matrix"
#set transform_value #[ Input parameters Filename getValue ]\n[ Input getTransform ]
#set outfile [open $doc w]
#puts $outfile "$transform_value"
#close $outfile


}

