# Amira
# Generated by Amira 6.3.011

proc affineRegistration {saveDir fullBrainFile innerBrainFile std_fullBrainFile std_innerBrainFile t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15} {
set hideNewModules 0
[ load $fullBrainFile ] setLabel fullBrainFile; fullBrainFile fire; 

[ load $innerBrainFile ] setLabel innerBrainFile; innerBrainFile fire; 

[ load $std_fullBrainFile ] setLabel std_fullBrainFile; std_fullBrainFile fire;
[ load $std_innerBrainFile ] setLabel std_innerBrainFile; std_innerBrainFile fire;


## do local registration
fullBrainFile setTransform $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 $t9 $t10 $t11 $t12 $t13 $t14 $t15
 
remove affineRegister
create HxAffineRegistration "affineRegister"
affineRegister model connect fullBrainFile
affineRegister reference connect std_fullBrainFile
#affineRegister reference2 connect std_innerBrainFile
affineRegister reference2 disconnect
affineRegister reference3 disconnect
affineRegister fire
affineRegister optimizer setIndex 0 0
affineRegister optimizer setIndex 1 0
affineRegister extensiveSearch setValue 0 0
affineRegister extensiveSearch setToggleVisible 0 1
affineRegister step setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister step setValue 0 394.200012207031
affineRegister step setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister step setValue 1 0.16666667163372
affineRegister nLevelsGradient setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister nLevelsGradient setValue 0 1
affineRegister nLevelsGradient setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister nLevelsGradient setValue 1 9.99999974737875e-05
affineRegister coarsestResolution setMinMax 0 1 985
affineRegister coarsestResolution setValue 0 8
affineRegister coarsestResolution setMinMax 1 1 489
affineRegister coarsestResolution setValue 1 8
affineRegister coarsestResolution setMinMax 2 1 131
affineRegister coarsestResolution setValue 2 3
affineRegister metric setIndex 0 0
affineRegister histogramRangeRef setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeRef setValue 0 0
affineRegister histogramRangeRef setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeRef setValue 1 4095
affineRegister histogramRangeMod setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeMod setValue 0 0
affineRegister histogramRangeMod setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeMod setValue 1 4095
affineRegister histogramBins setMinMax 0 -16777216 16777216
affineRegister histogramBins setValue 0 255
affineRegister histogramBins setMinMax 1 -16777216 16777216
affineRegister histogramBins setValue 1 255
#affineRegister thresholdModelOutsideReference setMinMax 0 1
#affineRegister thresholdModelOutsideReference setButtons 0
#affineRegister thresholdModelOutsideReference setEditButton 1
#affineRegister thresholdModelOutsideReference setIncrement 0.1
#affineRegister thresholdModelOutsideReference setValue 0.2
#affineRegister thresholdModelOutsideReference setSubMinMax 0 1
affineRegister options setValue 0 1
affineRegister options setToggleVisible 0 1
#affineRegister localizers setValue 0 0
#affineRegister localizers setToggleVisible 0 1
affineRegister transform setValue 0 1
affineRegister transform setToggleVisible 0 1
affineRegister transform setValue 1 0
affineRegister transform setToggleVisible 1 1
affineRegister transform setValue 2 1
affineRegister transform setToggleVisible 2 1
affineRegister transform setValue 3 0
affineRegister transform setToggleVisible 3 1
#affineRegister disableRotation setValue 0 0
#affineRegister disableRotation setToggleVisible 0 1
affineRegister register setValue 1
#affineRegister applyTransformToResult 1
#affineRegister doIt setValue hit 1
#affineRegister doIt hit
affineRegister action setValue 2
affineRegister action setValue hit 1
affineRegister action setValue 2
affineRegister fire



## Get transform matrix
set data [ fullBrainFile getTransform ]
set t0 [lindex $data 0]
set t1 [lindex $data 1]
set t2 [lindex $data 2]
set t3 [lindex $data 3]
set t4 [lindex $data 4]
set t5 [lindex $data 5]
set t6 [lindex $data 6]
set t7 [lindex $data 7]
set t8 [lindex $data 8]
set t9 [lindex $data 9]
set t10 [lindex $data 10]
set t11 [lindex $data 11]
set t12 [lindex $data 12]
set t13 [lindex $data 13]
set t14 [lindex $data 14]
set t15 [lindex $data 15]

## innerBrainFile setTransform
innerBrainFile setTransform $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 $t9 $t10 $t11 $t12 $t13 $t14 $t15

## innerBrainFile affine registration
remove affineRegister
create HxAffineRegistration "affineRegister"
affineRegister model connect innerBrainFile
affineRegister reference connect std_innerBrainFile
affineRegister reference2 disconnect
affineRegister reference3 disconnect
affineRegister fire
affineRegister optimizer setIndex 0 0
affineRegister optimizer setIndex 1 0
affineRegister extensiveSearch setValue 0 0
affineRegister extensiveSearch setToggleVisible 0 1
affineRegister step setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister step setValue 0 394.200012207031
affineRegister step setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister step setValue 1 0.16666667163372
affineRegister nLevelsGradient setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister nLevelsGradient setValue 0 1
affineRegister nLevelsGradient setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister nLevelsGradient setValue 1 9.99999974737875e-05
affineRegister coarsestResolution setMinMax 0 1 985
affineRegister coarsestResolution setValue 0 8
affineRegister coarsestResolution setMinMax 1 1 489
affineRegister coarsestResolution setValue 1 8
affineRegister coarsestResolution setMinMax 2 1 131
affineRegister coarsestResolution setValue 2 3
affineRegister metric setIndex 0 0
affineRegister histogramRangeRef setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeRef setValue 0 0
affineRegister histogramRangeRef setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeRef setValue 1 4095
affineRegister histogramRangeMod setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeMod setValue 0 0
affineRegister histogramRangeMod setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
affineRegister histogramRangeMod setValue 1 4095
affineRegister histogramBins setMinMax 0 -16777216 16777216
affineRegister histogramBins setValue 0 255
affineRegister histogramBins setMinMax 1 -16777216 16777216
affineRegister histogramBins setValue 1 255
#affineRegister thresholdModelOutsideReference setMinMax 0 1
#affineRegister thresholdModelOutsideReference setButtons 0
#affineRegister thresholdModelOutsideReference setEditButton 1
#affineRegister thresholdModelOutsideReference setIncrement 0.1
#affineRegister thresholdModelOutsideReference setValue 0.2
#affineRegister thresholdModelOutsideReference setSubMinMax 0 1
affineRegister options setValue 0 1
affineRegister options setToggleVisible 0 1
#affineRegister localizers setValue 0 0
#affineRegister localizers setToggleVisible 0 1
affineRegister transform setValue 0 1
affineRegister transform setToggleVisible 0 1
affineRegister transform setValue 1 0
affineRegister transform setToggleVisible 1 1
affineRegister transform setValue 2 1
affineRegister transform setToggleVisible 2 1
affineRegister transform setValue 3 0
affineRegister transform setToggleVisible 3 1
#affineRegister disableRotation setValue 0 0
#affineRegister disableRotation setToggleVisible 0 1
affineRegister register setValue 1
#affineRegister applyTransformToResult 1
#affineRegister doIt setValue hit 1
#affineRegister doIt hit
affineRegister action setValue 2
affineRegister action setValue hit 1
affineRegister action setValue 2
affineRegister fire

set doc "$saveDir/[file rootname [file tail [fullBrainFile parameters Filename getValue]]].affineMatrix"
set transform_value #[ fullBrainFile parameters Filename getValue ]\n[ fullBrainFile getTransform ]
set outfile [open $doc w]
puts $outfile "$transform_value"
close $outfile


set doc "$saveDir/[file rootname [file tail [innerBrainFile parameters Filename getValue]]].affineMatrix"
set transform_value #[ innerBrainFile parameters Filename getValue ]\n[ innerBrainFile getTransform ]
set outfile [open $doc w]
puts $outfile "$transform_value"
close $outfile


}

